apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fabric.fullname" . }}
  labels:
    {{- include "fabric.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fabric.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fabric.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: fabric
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "fabric.fullname" . }}
            - secretRef:
                name: {{ include "fabric.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
